---
bundle:
  name: miasma
  type: foreign
  install: "/usr/bin/touch /tmp/miasma.installed"
templates: []
permissions: []
rules: []
commands:
- name: list
  version: 0.1.1
  executable: commands/miasma-list
  enforcing: false
  calling_convention: bound
  documentation: 'List Stacks: `miasma:list`'
  options: []
- name: find
  version: 0.1.1
  executable: commands/miasma-find
  enforcing: false
  calling_convention: bound
  documentation: 'Find Stacks by Name: `miasma:find <search string>`'
  options: []
- name: describe
  version: 0.1.1
  executable: commands/miasma-describe
  enforcing: false
  calling_convention: bound
  documentation: 'Describe Stack: `miasma:describe <stack name>`'
  options: []
