#!/usr/bin/env ruby

require 'miasma'

search_string = ENV.fetch("COG_ARGV_0", ARGV[0])
region = ENV['COG_ARGV_1'] || ARGV[1] || ENV['AWS_REGION']

cloud = Miasma.api(:type => :orchestration,
                   :provider => :aws,
                   :credentials => {
                     :aws_access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                     :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                     :aws_region => region
                   })

puts cloud.stacks.all.first.name

stack = cloud.stacks.all.select { |stack| stack.name.include? search_string }

puts stack.map(&:name)
