#!/usr/bin/env ruby

require 'miasma'

stack = ENV.fetch("COG_ARGV_0", ARGV[0])

cloud = Miasma.api(:type => :orchestration,
                   :provider => :aws,
                   :credentials => {
                     :aws_access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                     :aws_secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                     :aws_region => ENV['AWS_REGION']
                   })
if cloud.stacks.all.map(&:name).include?(stack)
  puts "Outputs for #{stack}:"
  puts cloud.stacks.get(stack).outputs.map{ |o| "#{o.key}: #{o.value}" }
else
  puts "Stack Not Found"
end
